import { JobPostFormData } from './components';

export const jobCardsConfig: JobPostFormData[] = [
  {
    id: '498d9fac-208c-4e14-b90d-fe84470919f1',
    companyId: '26842876-cbbf-4f94-99dc-2221a601fa00',
    jobTitle: 'Junior DevOps Developer',
    companyName: 'TechNova',
    companyDescription:
      '## O nas\n**TechNova** — Projektujemy i wdrażamy aplikacje mobilne dla startupów i korporacji.',
    companyLogoUrl:
      'https://res.cloudinary.com/diur3hroj/image/upload/v1749847636/w1wugbe0eet0kmbu3hpd.jpg',
    level: 'junior',
    specialization: 'devops',
    contractType: 'full-time',
    workMode: 'remote',
    vacancies: '3',
    technologies: ['aws', 'git', 'sql', 'docker'],
    technologiesLevels: {
      sql: 2,
      git: 3,
      docker: 2,
      aws: 2,
    },
    isSalaryRange: true,
    minSalary: 5000,
    maxSalary: 8500,
    salary: 4900,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['german', 'french'],
    languageLevels: {
      german: 'a1',
      french: 'a2',
    },
    positionDescription:
      '## Zakres obowiązków\nProjektuj architekturę systemu oraz dbaj o wydajność aplikacji.',
    address: 'Wrocław, Polska',
    addressLat: 51.1079,
    addressLon: 17.0385,
    createdAt: '2025-05-26',
    isNew: false,
    endDate: '2025-07-21',
  },
  {
    id: 'e732e522-3edb-4c8c-a9c4-2e0a55485867',
    companyId: '1ad316b5-fa23-4b9c-aaef-2f033d2e33b9',
    jobTitle: 'Mid System Developer',
    companyName: 'CloudSpark',
    companyDescription:
      '## O nas\n**CloudSpark** — Nasze produkty wspierają zarządzanie danymi i procesami biznesowymi.',
    companyLogoUrl:
      'https://res.cloudinary.com/diur3hroj/image/upload/v1749919452/kcko4qbxjrovbqgb1ahf.jpg',
    level: 'manager',
    specialization: 'pm',
    contractType: 'part-time',
    workMode: 'hybrid',
    vacancies: '3',
    technologies: ['sql', 'docker', 'java'],
    technologiesLevels: {
      sql: 4,
      docker: 5,
      javascript: 1,
    },
    isSalaryRange: true,
    minSalary: 45,
    maxSalary: 60,
    salary: 28800,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perHour',
    languages: ['spanish', 'german'],
    languageLevels: {
      spanish: 'a2',
      german: 'a1',
    },
    positionDescription:
      '## Zakres obowiązków\nProjektuj architekturę systemu oraz dbaj o wydajność aplikacji.',
    address: 'Gdańsk, Polska',
    addressLat: 54.352,
    addressLon: 18.6466,
    createdAt: '2025-05-26',
    isNew: false,
    endDate: '2025-06-13',
  },
  {
    id: '0ef958e1-65da-47fd-8153-edd29647ef5c',
    companyId: '70805213-a7c3-42d9-879f-a872b7aec985',
    jobTitle: 'Senior Cloud Developer',
    companyName: 'DataPulse',
    companyDescription:
      '## O nas\n**DataPulse** — Dostarczamy nowoczesne rozwiązania DevOps dla firm z całej Europy.',
    companyLogoUrl:
      'https://res.cloudinary.com/diur3hroj/image/upload/v1749919500/kqqduxcoefjoq4808iqz.png',
    level: 'mid',
    specialization: 'qa',
    contractType: 'contract',
    workMode: 'remote',
    vacancies: '4',
    technologies: ['sql', 'aws'],
    technologiesLevels: {
      sql: 4,
      aws: 3,
    },
    isSalaryRange: true,
    minSalary: 16000,
    maxSalary: 22000,
    salary: 11400,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['italian'],
    languageLevels: {
      italian: 'b2',
    },
    positionDescription:
      '## Zakres obowiązków\nUczestnicz w procesie tworzenia interfejsów użytkownika zgodnie z wymaganiami UX/UI.',
    address: 'Warszawa, Polska',
    addressLat: 52.2297,
    addressLon: 21.0122,
    createdAt: '2025-05-22',
    isNew: false,
    endDate: '2025-06-10',
  },
  {
    id: 'aacba6ec-5bf7-4dc4-9a3f-cd6c9e8e174e',
    companyId: '5a535147-2555-4bd4-9c78-735f97c30a24',
    jobTitle: 'Junior System Engineer',
    companyName: 'NextGenSoft',
    companyDescription:
      '## O nas\n**NextGenSoft** — Projektujemy i wdrażamy aplikacje mobilne dla startupów i korporacji.',
    companyLogoUrl:
      'https://res.cloudinary.com/diur3hroj/image/upload/v1749919489/pfat88rm6oarotqel34q.png',
    level: 'manager',
    specialization: 'qa',
    contractType: 'b2b',
    workMode: 'hybrid',
    vacancies: '3',
    technologies: ['sql', 'python'],
    technologiesLevels: {
      sql: 2,
      python: 2,
    },
    isSalaryRange: true,
    minSalary: 7000,
    maxSalary: 11500,
    salary: 28400,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['german'],
    languageLevels: {
      german: 'c1',
    },
    positionDescription:
      '## Zakres obowiązków\nBędziesz odpowiedzialny/a za rozwój i utrzymanie komponentów frontendowych w React.',
    address: 'Kraków, Polska',
    addressLat: 50.0647,
    addressLon: 19.945,
    createdAt: '2025-06-09',
    isNew: true,
    endDate: '2025-07-14',
  },
  {
    id: '1897fc56-713b-4a2a-b6b0-dd3973f00cba',
    companyId: '28e7af11-5ddb-4dd4-a88e-f8577e51d0f4',
    jobTitle: 'Junior Software Engineer',
    companyName: 'BrightApps',
    companyDescription:
      '## O nas\n**BrightApps** — Jesteśmy software housem specjalizującym się w aplikacjach webowych.',
    companyLogoUrl:
      'https://res.cloudinary.com/diur3hroj/image/upload/v1749919540/cdwgmool22bc7k1k7pe7.jpg',
    level: 'intern',
    specialization: 'backend',
    contractType: 'full-time',
    workMode: 'office',
    vacancies: '5',
    technologies: ['python', 'aws', 'sql'],
    technologiesLevels: {
      react: 2,
      java: 1,
      python: 3,
      aws: 5,
      sql: 5,
    },
    isSalaryRange: true,
    minSalary: 4900,
    maxSalary: 7500,
    salary: 4900,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['english'],
    languageLevels: {
      english: 'c2',
    },
    positionDescription:
      '## Zakres obowiązków\nTwórz i rozwijaj backend oparty na Node.js i bazach danych NoSQL.',
    address: 'Warszawa, Polska',
    addressLat: 52.2297,
    addressLon: 21.0122,
    createdAt: '2025-05-31',
    isNew: false,
    endDate: '2025-07-21',
  },
  {
    id: '0b77b7ce-efd7-4d9b-a415-be55eba76900',
    companyId: '4137ee0d-3457-457f-be56-9a04f78f494d',
    jobTitle: 'Mid Fullstack Specialist',
    companyName: 'InnoWare',
    companyDescription:
      '## O nas\n**InnoWare** — Jesteśmy software housem specjalizującym się w aplikacjach webowych.',
    companyLogoUrl:
      'https://res.cloudinary.com/diur3hroj/image/upload/v1749919557/b1ejh2bw1ka0igkzc7ni.avif',
    level: 'mid',
    specialization: 'mobile',
    contractType: 'full-time',
    workMode: 'hybrid',
    vacancies: '3',
    technologies: ['docker', 'nodejs', 'typescript', 'react'],
    technologiesLevels: {
      kubernetes: 2,
      nodejs: 5,
      java: 3,
    },
    isSalaryRange: true,
    minSalary: 12000,
    maxSalary: 16000,
    salary: 15000,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['english', 'spanish'],
    languageLevels: {
      english: 'a2',
      spanish: 'b1',
    },
    positionDescription:
      '## Zakres obowiązków\nPracuj w zespole SCRUM przy realizacji projektów webowych dla klientów z UE.',
    address: 'Poznań, Polska',
    addressLat: 52.4064,
    addressLon: 16.9252,
    createdAt: '2025-05-15',
    isNew: false,
    endDate: '2025-06-26',
  },
  {
    id: '1e4d9f5a-8762-4e30-bd62-a8ae4a68be5d',
    companyId: 'c8937a81-63a6-43ac-bd78-ea213585eb2b',
    jobTitle: 'Intern Jest Tester',
    companyName: 'DigitalCraft',
    companyDescription:
      '## O nas\n**DigitalCraft** — Jesteśmy software housem specjalizującym się w aplikacjach webowych.',
    companyLogoUrl:
      'https://res.cloudinary.com/diur3hroj/image/upload/v1749919570/vrxnwrdx5tjhwxdnhmbz.jpg',
    level: 'senior',
    specialization: 'data-engineering',
    contractType: 'internship',
    workMode: 'remote',
    vacancies: '1',
    technologies: ['jest', 'django'],
    technologiesLevels: {
      java: 4,
      docker: 2,
      react: 4,
      sql: 1,
    },
    isSalaryRange: true,
    minSalary: 6000,
    maxSalary: 9000,
    salary: 18500,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['french', 'spanish'],
    languageLevels: {
      french: 'c2',
      spanish: 'b2',
    },
    positionDescription:
      '## Zakres obowiązków\nProjektuj architekturę systemu oraz dbaj o wydajność aplikacji.',
    address: 'Poznań, Polska',
    addressLat: 52.4064,
    addressLon: 16.9252,
    createdAt: '2025-05-23',
    isNew: false,
    endDate: '2025-07-09',
  },
  {
    id: '65b8c400-48dc-403c-aa0f-08c30156c4d0',
    companyId: 'a24b1d43-a477-4f1e-b041-0f0679a83a1c',
    jobTitle: 'Junior Fullstack Specialist',
    companyName: 'SkyNetics',
    companyDescription:
      '## O nas\n**SkyNetics** — Projektujemy i wdrażamy aplikacje mobilne dla startupów i korporacji.',
    companyLogoUrl:
      'https://res.cloudinary.com/diur3hroj/image/upload/v1749921065/haubpev3aopertocsblp.png',
    level: 'lead',
    specialization: 'backend',
    contractType: 'internship',
    workMode: 'office',
    vacancies: '3',
    technologies: ['react', 'javascript', 'kubernetes', 'java'],
    technologiesLevels: {
      react: 4,
      javascript: 3,
      kubernetes: 2,
      java: 4,
    },
    isSalaryRange: true,
    minSalary: 25900,
    maxSalary: 30000,
    salary: 25900,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['english', 'german'],
    languageLevels: {
      english: 'a1',
      german: 'c2',
    },
    positionDescription:
      '## Zakres obowiązków\nPracuj w zespole SCRUM przy realizacji projektów webowych dla klientów z UE.',
    address: 'Berlin, Polska',
    addressLat: 52.52,
    addressLon: 13.405,
    createdAt: '2025-05-30',
    isNew: false,
    endDate: '2025-07-14',
  },
  {
    id: 'd17e05f2-d1ba-4cb8-8eee-f5ff2a144e4b',
    companyId: '17c1483e-541c-4cb0-8ac3-03f7e7f4db4a',
    jobTitle: 'Senior Backend Developer',
    companyName: 'PixelForge',
    companyDescription:
      '## O nas\n**PixelForge** — Tworzymy rozwiązania chmurowe dla branży e-commerce i finansowej.',
    companyLogoUrl:
      'https://res.cloudinary.com/diur3hroj/image/upload/v1749921097/ejf9agnhg0estqvoldiz.png',
    level: 'mid',
    specialization: 'qa',
    contractType: 'full-time',
    workMode: 'office',
    vacancies: '3',
    technologies: ['java', 'sql', 'docker'],
    technologiesLevels: {
      typescript: 4,
      java: 2,
      sql: 5,
    },
    isSalaryRange: true,
    minSalary: 17000,
    maxSalary: 22000,
    salary: 15000,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['german', 'french'],
    languageLevels: {
      german: 'a1',
      french: 'b2',
    },
    positionDescription:
      '## Zakres obowiązków\nUczestnicz w procesie tworzenia interfejsów użytkownika zgodnie z wymaganiami UX/UI.',
    address: 'Gdańsk, Polska',
    addressLat: 54.352,
    addressLon: 18.6466,
    createdAt: '2025-06-08',
    isNew: true,
    endDate: '2025-08-06',
  },
  {
    id: '4e003899-af49-4246-9c72-4fd433a18862',
    companyId: '19cb5666-ca46-4503-8e8e-0e690c0f5f26',
    jobTitle: 'Senior Engineer',
    companyName: 'DevHaven',
    companyDescription:
      '## O nas\n**DevHaven** — Tworzymy rozwiązania chmurowe dla branży e-commerce i finansowej.',
    companyLogoUrl: 'https://via.placeholder.com/150?text=DevHaven',
    level: 'senior',
    specialization: 'fullstack',
    contractType: 'internship',
    workMode: 'hybrid',
    vacancies: '5',
    technologies: ['python', 'aws', 'docker', 'kubernetes', 'nodejs'],
    technologiesLevels: {
      python: 4,
      aws: 5,
      docker: 2,
      kubernetes: 3,
      nodejs: 2,
    },
    isSalaryRange: true,
    minSalary: 20300,
    maxSalary: 24600,
    salary: 20300,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['english', 'italian'],
    languageLevels: {
      english: 'b2',
      italian: 'b2',
    },
    positionDescription:
      '## Zakres obowiązków\nUczestnicz w procesie tworzenia interfejsów użytkownika zgodnie z wymaganiami UX/UI.',
    address: 'Poznań, Polska',
    addressLat: 52.4064,
    addressLon: 16.9252,
    createdAt: '2025-06-04',
    isNew: false,
    endDate: '2025-07-17',
  },
  {
    id: 'a544d87e-c997-4c66-90f5-858b38246d55',
    companyId: '1bd976d7-2d0b-49d8-bde5-bf11f19e035a',
    jobTitle: 'Junior Specialist',
    companyName: 'TechNova',
    companyDescription:
      '## O nas\n**TechNova** — Tworzymy rozwiązania chmurowe dla branży e-commerce i finansowej.',
    companyLogoUrl: 'https://via.placeholder.com/150?text=TechNova',
    level: 'junior',
    specialization: 'frontend',
    contractType: 'internship',
    workMode: 'office',
    vacancies: '5',
    technologies: ['typescript', 'react', 'kubernetes', 'docker', 'sql'],
    technologiesLevels: {
      typescript: 5,
      react: 4,
      kubernetes: 5,
      docker: 3,
      sql: 2,
    },
    isSalaryRange: true,
    minSalary: 6200,
    maxSalary: 10200,
    salary: 6200,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['italian', 'french'],
    languageLevels: {
      italian: 'c2',
      french: 'b1',
    },
    positionDescription:
      '## Zakres obowiązków\nTwórz i rozwijaj backend oparty na Node.js i bazach danych NoSQL.',
    address: 'Berlin, Polska',
    addressLat: 52.52,
    addressLon: 13.405,
    createdAt: '2025-05-31',
    isNew: false,
    endDate: '2025-07-16',
  },
  {
    id: 'ae0087cd-2b44-4446-a55e-2fd375e441d7',
    companyId: '00f5712f-b636-4d97-bdb0-158c8fcb192d',
    jobTitle: 'Senior Specialist',
    companyName: 'CloudSpark',
    companyDescription:
      '## O nas\n**CloudSpark** — Tworzymy rozwiązania chmurowe dla branży e-commerce i finansowej.',
    companyLogoUrl: 'https://via.placeholder.com/150?text=CloudSpark',
    level: 'senior',
    specialization: 'mobile',
    contractType: 'full-time',
    workMode: 'hybrid',
    vacancies: '5',
    technologies: ['sql', 'aws', 'javascript'],
    technologiesLevels: {
      sql: 5,
      aws: 1,
      javascript: 3,
    },
    isSalaryRange: true,
    minSalary: 19200,
    maxSalary: 24100,
    salary: 19200,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['french'],
    languageLevels: {
      french: 'a2',
    },
    positionDescription:
      '## Zakres obowiązków\nUczestnicz w procesie tworzenia interfejsów użytkownika zgodnie z wymaganiami UX/UI.',
    address: 'Warszawa, Polska',
    addressLat: 52.2297,
    addressLon: 21.0122,
    createdAt: '2025-05-20',
    isNew: false,
    endDate: '2025-07-01',
  },
  {
    id: '13d3c7ea-320b-42ea-8bc9-986de09be3b3',
    companyId: 'b3954766-800a-4449-a3a8-8e56265037d6',
    jobTitle: 'Senior Engineer',
    companyName: 'DataPulse',
    companyDescription:
      '## O nas\n**DataPulse** — Nasze produkty wspierają zarządzanie danymi i procesami biznesowymi.',
    companyLogoUrl: 'https://via.placeholder.com/150?text=DataPulse',
    level: 'lead',
    specialization: 'data-engineering',
    contractType: 'contract',
    workMode: 'office',
    vacancies: '4',
    technologies: ['react', 'java', 'sql', 'javascript', 'kubernetes'],
    technologiesLevels: {
      react: 1,
      java: 2,
      sql: 5,
      javascript: 1,
      kubernetes: 1,
    },
    isSalaryRange: true,
    minSalary: 22800,
    maxSalary: 25800,
    salary: 22800,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['spanish', 'english'],
    languageLevels: {
      spanish: 'a2',
      english: 'a1',
    },
    positionDescription:
      '## Zakres obowiązków\nTwórz i rozwijaj backend oparty na Node.js i bazach danych NoSQL.',
    address: 'Gdańsk, Polska',
    addressLat: 54.352,
    addressLon: 18.6466,
    createdAt: '2025-06-09',
    isNew: true,
    endDate: '2025-07-17',
  },
  {
    id: 'dd029617-9fb6-46ff-8afe-fef0ba40c729',
    companyId: 'f4796d19-c1d9-4199-ae00-45408d953d32',
    jobTitle: 'Mid Specialist',
    companyName: 'NextGenSoft',
    companyDescription:
      '## O nas\n**NextGenSoft** — Jesteśmy software housem specjalizującym się w aplikacjach webowych.',
    companyLogoUrl: 'https://via.placeholder.com/150?text=NextGenSoft',
    level: 'lead',
    specialization: 'fullstack',
    contractType: 'part-time',
    workMode: 'remote',
    vacancies: '1',
    technologies: ['python', 'aws', 'nodejs', 'java', 'react'],
    technologiesLevels: {
      python: 1,
      aws: 5,
      nodejs: 4,
      java: 1,
      react: 5,
    },
    isSalaryRange: true,
    minSalary: 25700,
    maxSalary: 29000,
    salary: 25700,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['french'],
    languageLevels: {
      french: 'a1',
    },
    positionDescription:
      '## Zakres obowiązków\nPracuj w zespole SCRUM przy realizacji projektów webowych dla klientów z UE.',
    address: 'Kraków, Polska',
    addressLat: 50.0647,
    addressLon: 19.945,
    createdAt: '2025-05-26',
    isNew: false,
    endDate: '2025-07-04',
  },
  {
    id: '6d25c772-eef4-430f-9a66-30e59f3d4a61',
    companyId: 'b48d8ab5-8a5f-4e40-bd78-f3bb0d6c6e1c',
    jobTitle: 'Mid Engineer',
    companyName: 'BrightApps',
    companyDescription:
      '## O nas\n**BrightApps** — Tworzymy rozwiązania chmurowe dla branży e-commerce i finansowej.',
    companyLogoUrl: 'https://via.placeholder.com/150?text=BrightApps',
    level: 'mid',
    specialization: 'qa',
    contractType: 'full-time',
    workMode: 'remote',
    vacancies: '5',
    technologies: ['python', 'java', 'aws', 'docker', 'react'],
    technologiesLevels: {
      python: 5,
      java: 4,
      aws: 5,
      docker: 2,
      react: 2,
    },
    isSalaryRange: true,
    minSalary: 12700,
    maxSalary: 16200,
    salary: 12700,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['english', 'italian'],
    languageLevels: {
      english: 'c1',
      italian: 'a1',
    },
    positionDescription:
      '## Zakres obowiązków\nUczestnicz w procesie tworzenia interfejsów użytkownika zgodnie z wymaganiami UX/UI.',
    address: 'Warszawa, Polska',
    addressLat: 52.2297,
    addressLon: 21.0122,
    createdAt: '2025-06-05',
    isNew: false,
    endDate: '2025-06-22',
  },
  {
    id: 'e61af15c-6e3d-4f00-be91-b784009879fa',
    companyId: '138e503c-4a05-411d-b1fe-73bcbc296057',
    jobTitle: 'Junior Developer',
    companyName: 'InnoWare',
    companyDescription:
      '## O nas\n**InnoWare** — Projektujemy i wdrażamy aplikacje mobilne dla startupów i korporacji.',
    companyLogoUrl: 'https://via.placeholder.com/150?text=InnoWare',
    level: 'lead',
    specialization: 'qa',
    contractType: 'b2b',
    workMode: 'remote',
    vacancies: '2',
    technologies: ['kubernetes', 'nodejs'],
    technologiesLevels: {
      kubernetes: 3,
      nodejs: 3,
    },
    isSalaryRange: true,
    minSalary: 24100,
    maxSalary: 29900,
    salary: 24100,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['spanish', 'italian'],
    languageLevels: {
      spanish: 'a2',
      italian: 'b1',
    },
    positionDescription:
      '## Zakres obowiązków\nBędziesz odpowiedzialny/a za rozwój i utrzymanie komponentów frontendowych w React.',
    address: 'Gdańsk, Polska',
    addressLat: 54.352,
    addressLon: 18.6466,
    createdAt: '2025-06-01',
    isNew: false,
    endDate: '2025-07-06',
  },
  {
    id: '87f781e6-932b-421a-a055-5408fe8d22b9',
    companyId: 'e703b454-2118-450b-8850-eeafa062ca44',
    jobTitle: 'Mid Developer',
    companyName: 'DigitalCraft',
    companyDescription:
      '## O nas\n**DigitalCraft** — Nasze produkty wspierają zarządzanie danymi i procesami biznesowymi.',
    companyLogoUrl: 'https://via.placeholder.com/150?text=DigitalCraft',
    level: 'junior',
    specialization: 'data-engineering',
    contractType: 'part-time',
    workMode: 'remote',
    vacancies: '2',
    technologies: ['java', 'react', 'kubernetes'],
    technologiesLevels: {
      java: 2,
      react: 5,
      kubernetes: 5,
    },
    isSalaryRange: true,
    minSalary: 8000,
    maxSalary: 11000,
    salary: 8000,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['spanish'],
    languageLevels: {
      spanish: 'a2',
    },
    positionDescription:
      '## Zakres obowiązków\nPracuj w zespole SCRUM przy realizacji projektów webowych dla klientów z UE.',
    address: 'Warszawa, Polska',
    addressLat: 52.2297,
    addressLon: 21.0122,
    createdAt: '2025-05-19',
    isNew: false,
    endDate: '2025-06-28',
  },
  {
    id: '83e95654-27a6-4ef2-8ad0-8ff9d6063308',
    companyId: '689e3196-1f94-469e-aee5-e67b861e7388',
    jobTitle: 'Junior Developer',
    companyName: 'SkyNetics',
    companyDescription:
      '## O nas\n**SkyNetics** — Jesteśmy software housem specjalizującym się w aplikacjach webowych.',
    companyLogoUrl: 'https://via.placeholder.com/150?text=SkyNetics',
    level: 'intern',
    specialization: 'frontend',
    contractType: 'full-time',
    workMode: 'remote',
    vacancies: '5',
    technologies: ['typescript', 'docker', 'java', 'javascript'],
    technologiesLevels: {
      typescript: 4,
      docker: 4,
      java: 1,
      javascript: 4,
    },
    isSalaryRange: true,
    minSalary: 4900,
    maxSalary: 6000,
    salary: 4900,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['french'],
    languageLevels: {
      french: 'c2',
    },
    positionDescription:
      '## Zakres obowiązków\nBędziesz odpowiedzialny/a za rozwój i utrzymanie komponentów frontendowych w React.',
    address: 'Berlin, Polska',
    addressLat: 52.52,
    addressLon: 13.405,
    createdAt: '2025-06-09',
    isNew: true,
    endDate: '2025-07-15',
  },
  {
    id: 'f3fba69d-1301-42d4-9436-e2c24bfa1960',
    companyId: '933695af-874f-4a66-a032-90bdf88238d1',
    jobTitle: 'Senior Engineer',
    companyName: 'PixelForge',
    companyDescription:
      '## O nas\n**PixelForge** — Dostarczamy nowoczesne rozwiązania DevOps dla firm z całej Europy.',
    companyLogoUrl: 'https://via.placeholder.com/150?text=PixelForge',
    level: 'mid',
    specialization: 'data-engineering',
    contractType: 'internship',
    workMode: 'hybrid',
    vacancies: '2',
    technologies: ['javascript', 'aws', 'python', 'sql', 'kubernetes'],
    technologiesLevels: {
      javascript: 1,
      aws: 4,
      python: 3,
      sql: 3,
      kubernetes: 2,
    },
    isSalaryRange: true,
    minSalary: 13400,
    maxSalary: 17600,
    salary: 13400,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['spanish', 'french'],
    languageLevels: {
      spanish: 'c1',
      french: 'c2',
    },
    positionDescription:
      '## Zakres obowiązków\nProjektuj architekturę systemu oraz dbaj o wydajność aplikacji.',
    address: 'Poznań, Polska',
    addressLat: 52.4064,
    addressLon: 16.9252,
    createdAt: '2025-05-16',
    isNew: false,
    endDate: '2025-06-29',
  },
  {
    id: '42cebd02-0ef1-450e-af9d-e1bff4f92d5f',
    companyId: '0e845cf1-46a0-467e-8dda-7bb8477539e6',
    jobTitle: 'Senior Developer',
    companyName: 'DevHaven',
    companyDescription:
      '## O nas\n**DevHaven** — Jesteśmy software housem specjalizującym się w aplikacjach webowych.',
    companyLogoUrl: 'https://via.placeholder.com/150?text=DevHaven',
    level: 'manager',
    specialization: 'frontend',
    contractType: 'full-time',
    workMode: 'hybrid',
    vacancies: '4',
    technologies: ['javascript', 'typescript'],
    technologiesLevels: {
      javascript: 3,
      typescript: 2,
    },
    isSalaryRange: true,
    minSalary: 28000,
    maxSalary: 33700,
    salary: 28000,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['spanish', 'italian'],
    languageLevels: {
      spanish: 'b1',
      italian: 'b1',
    },
    positionDescription:
      '## Zakres obowiązków\nUczestnicz w procesie tworzenia interfejsów użytkownika zgodnie z wymaganiami UX/UI.',
    address: 'Poznań, Polska',
    addressLat: 52.4064,
    addressLon: 16.9252,
    createdAt: '2025-06-03',
    isNew: false,
    endDate: '2025-07-24',
  },
  {
    id: '71531858-bda9-4523-87e3-0d358f85e53f',
    companyId: 'eecbf312-be9a-4ede-8762-e44b779f2e44',
    jobTitle: 'Mid Specialist',
    companyName: 'TechNova',
    companyDescription:
      '## O nas\n**TechNova** — Tworzymy rozwiązania chmurowe dla branży e-commerce i finansowej.',
    companyLogoUrl: 'https://via.placeholder.com/150?text=TechNova',
    level: 'intern',
    specialization: 'devops',
    contractType: 'part-time',
    workMode: 'remote',
    vacancies: '1',
    technologies: ['java', 'python', 'nodejs', 'aws', 'docker'],
    technologiesLevels: {
      java: 4,
      python: 4,
      nodejs: 4,
      aws: 4,
      docker: 1,
    },
    isSalaryRange: true,
    minSalary: 4900,
    maxSalary: 6000,
    salary: 4900,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['spanish'],
    languageLevels: {
      spanish: 'c2',
    },
    positionDescription:
      '## Zakres obowiązków\nProjektuj architekturę systemu oraz dbaj o wydajność aplikacji.',
    address: 'Berlin, Polska',
    addressLat: 52.52,
    addressLon: 13.405,
    createdAt: '2025-05-15',
    isNew: false,
    endDate: '2025-06-12',
  },
  {
    id: '8200fa5f-49f5-415d-8fac-a9cf915069f7',
    companyId: '0f005a97-dd5a-47f2-b34a-ea220d039942',
    jobTitle: 'Junior DevOps Specialist',
    companyName: 'CloudSpark',
    companyDescription:
      '## O nas\n**CloudSpark** — Dostarczamy nowoczesne rozwiązania DevOps dla firm z całej Europy.',
    companyLogoUrl:
      'https://res.cloudinary.com/diur3hroj/image/upload/v1749921617/rwy6fdq3hbvce2gj0rty.png',
    level: 'junior',
    specialization: 'devops',
    contractType: 'full-time',
    workMode: 'remote',
    vacancies: '4',
    technologies: ['aws', 'jenkins', 'git'],
    technologiesLevels: {
      nodejs: 4,
      java: 2,
      kubernetes: 2,
    },
    isSalaryRange: true,
    minSalary: 5000,
    maxSalary: 9000,
    salary: 24800,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['english'],
    languageLevels: {
      english: 'c2',
    },
    positionDescription:
      '## Zakres obowiązków\nProjektuj architekturę systemu oraz dbaj o wydajność aplikacji.',
    address: 'Wrocław, Polska',
    addressLat: 51.1079,
    addressLon: 17.0385,
    createdAt: '2025-06-11',
    isNew: true,
    endDate: '2025-07-30',
  },
  {
    id: '10dba6e7-d9aa-4b07-8ecc-7f3f643c7f51',
    companyId: 'b97772d3-9a23-4600-9652-d129e794894f',
    jobTitle: 'Junior Engineer',
    companyName: 'DataPulse',
    companyDescription:
      '## O nas\n**DataPulse** — Nasze produkty wspierają zarządzanie danymi i procesami biznesowymi.',
    companyLogoUrl: 'https://via.placeholder.com/150?text=DataPulse',
    level: 'junior',
    specialization: 'data-engineering',
    contractType: 'internship',
    workMode: 'hybrid',
    vacancies: '1',
    technologies: ['aws', 'docker', 'typescript', 'sql', 'nodejs'],
    technologiesLevels: {
      aws: 2,
      docker: 5,
      typescript: 3,
      sql: 3,
      nodejs: 5,
    },
    isSalaryRange: true,
    minSalary: 6300,
    maxSalary: 10500,
    salary: 6300,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['french'],
    languageLevels: {
      french: 'c2',
    },
    positionDescription:
      '## Zakres obowiązków\nBędziesz odpowiedzialny/a za rozwój i utrzymanie komponentów frontendowych w React.',
    address: 'Berlin, Polska',
    addressLat: 52.52,
    addressLon: 13.405,
    createdAt: '2025-05-21',
    isNew: false,
    endDate: '2025-06-29',
  },
  {
    id: '89fd8c90-de95-45b1-a62f-8449678f7155',
    companyId: '01f9d05c-2dbe-4acc-a7fd-f0e2b6ae4d59',
    jobTitle: 'Senior Developer',
    companyName: 'NextGenSoft',
    companyDescription:
      '## O nas\n**NextGenSoft** — Nasze produkty wspierają zarządzanie danymi i procesami biznesowymi.',
    companyLogoUrl: 'https://via.placeholder.com/150?text=NextGenSoft',
    level: 'lead',
    specialization: 'mobile',
    contractType: 'part-time',
    workMode: 'remote',
    vacancies: '2',
    technologies: ['python', 'sql', 'nodejs'],
    technologiesLevels: {
      python: 1,
      sql: 1,
      nodejs: 1,
    },
    isSalaryRange: true,
    minSalary: 26900,
    maxSalary: 29900,
    salary: 26900,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['german', 'english'],
    languageLevels: {
      german: 'c2',
      english: 'c1',
    },
    positionDescription:
      '## Zakres obowiązków\nBędziesz odpowiedzialny/a za rozwój i utrzymanie komponentów frontendowych w React.',
    address: 'Warszawa, Polska',
    addressLat: 52.2297,
    addressLon: 21.0122,
    createdAt: '2025-05-18',
    isNew: false,
    endDate: '2025-06-05',
  },
  {
    id: '25faeb7a-17e7-4791-a031-869d70edc2dc',
    companyId: '83d476e2-90b5-42c7-ba01-6b70c902929c',
    jobTitle: 'Mid Engineer',
    companyName: 'BrightApps',
    companyDescription:
      '## O nas\n**BrightApps** — Projektujemy i wdrażamy aplikacje mobilne dla startupów i korporacji.',
    companyLogoUrl: 'https://via.placeholder.com/150?text=BrightApps',
    level: 'intern',
    specialization: 'data-engineering',
    contractType: 'part-time',
    workMode: 'remote',
    vacancies: '1',
    technologies: ['kubernetes', 'aws', 'react', 'javascript', 'python'],
    technologiesLevels: {
      kubernetes: 5,
      aws: 3,
      react: 3,
      javascript: 1,
      python: 1,
    },
    isSalaryRange: true,
    minSalary: 4900,
    maxSalary: 6000,
    salary: 4900,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['english'],
    languageLevels: {
      english: 'c2',
    },
    positionDescription:
      '## Zakres obowiązków\nUczestnicz w procesie tworzenia interfejsów użytkownika zgodnie z wymaganiami UX/UI.',
    address: 'Berlin, Polska',
    addressLat: 52.52,
    addressLon: 13.405,
    createdAt: '2025-05-31',
    isNew: false,
    endDate: '2025-07-30',
  },
  {
    id: 'e51b8fef-f1e5-4d40-a71a-11b1e8d11285',
    companyId: '3f3f76a7-ae7c-4311-92a9-d99d7edadfe3',
    jobTitle: 'Mid Specialist',
    companyName: 'InnoWare',
    companyDescription:
      '## O nas\n**InnoWare** — Jesteśmy software housem specjalizującym się w aplikacjach webowych.',
    companyLogoUrl: 'https://via.placeholder.com/150?text=InnoWare',
    level: 'mid',
    specialization: 'backend',
    contractType: 'contract',
    workMode: 'office',
    vacancies: '3',
    technologies: ['java', 'docker', 'typescript', 'kubernetes', 'react'],
    technologiesLevels: {
      java: 4,
      docker: 4,
      typescript: 1,
      kubernetes: 5,
      react: 5,
    },
    isSalaryRange: true,
    minSalary: 14300,
    maxSalary: 17500,
    salary: 14300,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['french'],
    languageLevels: {
      french: 'b1',
    },
    positionDescription:
      '## Zakres obowiązków\nUczestnicz w procesie tworzenia interfejsów użytkownika zgodnie z wymaganiami UX/UI.',
    address: 'Poznań, Polska',
    addressLat: 52.4064,
    addressLon: 16.9252,
    createdAt: '2025-05-30',
    isNew: false,
    endDate: '2025-06-16',
  },
  {
    id: '2d042f38-a972-422b-a7cf-8bba99a2fd40',
    companyId: '69216d37-7b65-4d72-a258-cff767aad59c',
    jobTitle: 'Junior Developer',
    companyName: 'DigitalCraft',
    companyDescription:
      '## O nas\n**DigitalCraft** — Jesteśmy software housem specjalizującym się w aplikacjach webowych.',
    companyLogoUrl: 'https://via.placeholder.com/150?text=DigitalCraft',
    level: 'senior',
    specialization: 'backend',
    contractType: 'internship',
    workMode: 'hybrid',
    vacancies: '4',
    technologies: ['python', 'nodejs', 'aws', 'react'],
    technologiesLevels: {
      python: 5,
      nodejs: 4,
      aws: 1,
      react: 3,
    },
    isSalaryRange: true,
    minSalary: 18700,
    maxSalary: 24800,
    salary: 18700,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['german', 'english'],
    languageLevels: {
      german: 'b2',
      english: 'c2',
    },
    positionDescription:
      '## Zakres obowiązków\nTwórz i rozwijaj backend oparty na Node.js i bazach danych NoSQL.',
    address: 'Berlin, Polska',
    addressLat: 52.52,
    addressLon: 13.405,
    createdAt: '2025-05-31',
    isNew: false,
    endDate: '2025-06-27',
  },
  {
    id: '00e11a17-3327-4f06-aba6-6f7c7634e30f',
    companyId: '27f65d49-7db5-41d7-9379-d275091de18c',
    jobTitle: 'Junior AWS Engineer',
    companyName: 'SkyNetics',
    companyDescription:
      '## O nas\n**SkyNetics** — Projektujemy i wdrażamy aplikacje mobilne dla startupów i korporacji.',
    companyLogoUrl:
      'https://res.cloudinary.com/diur3hroj/image/upload/v1749921710/a7azqt4wxdwwrwrrfjsm.jpg',
    level: 'junior',
    specialization: 'devops',
    contractType: 'full-time',
    workMode: 'remote',
    vacancies: '5',
    technologies: ['aws', 'cypress', 'linux', 'git'],
    technologiesLevels: {
      docker: 4,
      sql: 2,
      javascript: 5,
      nodejs: 2,
    },
    isSalaryRange: true,
    minSalary: 7000,
    maxSalary: 10000,
    salary: 19200,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['italian'],
    languageLevels: {
      italian: 'a1',
    },
    positionDescription:
      '## Zakres obowiązków\nUczestnicz w procesie tworzenia interfejsów użytkownika zgodnie z wymaganiami UX/UI.',
    address: 'Kielce, Polska',
    addressLat: 52.52,
    addressLon: 13.405,
    createdAt: '2025-05-22',
    isNew: false,
    endDate: '2025-07-13',
  },
  {
    id: 'cae3dead-87ab-4c0d-a727-e2ecce0ef50b',
    companyId: '29f147eb-cbec-4a3b-80b0-18870c768fe8',
    jobTitle: 'Junior DevOps Specialist',
    companyName: 'PixelForge',
    companyDescription:
      '## O nas\n**PixelForge** — Dostarczamy nowoczesne rozwiązania DevOps dla firm z całej Europy.',
    companyLogoUrl:
      'https://res.cloudinary.com/diur3hroj/image/upload/v1749921932/m4dtdmulurzivoo5hsg6.webp',
    level: 'junior',
    specialization: 'devops',
    contractType: 'full-time',
    workMode: 'remote',
    vacancies: '4',
    technologies: ['sql', 'kubernetes', 'aws', 'docker', 'git'],
    technologiesLevels: {
      sql: 1,
      kubernetes: 3,
    },
    isSalaryRange: true,
    minSalary: 6000,
    maxSalary: 9000,
    salary: 23000,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['english'],
    languageLevels: {
      english: 'c2',
    },
    positionDescription:
      '## Zakres obowiązków\nTwórz i rozwijaj backend oparty na Node.js i bazach danych NoSQL.',
    address: 'Kraków, Polska',
    addressLat: 50.0647,
    addressLon: 19.945,
    createdAt: '2025-06-08',
    isNew: true,
    endDate: '2025-07-23',
  },
  {
    id: 'c5b1f750-4030-42b9-953b-3d38efba6168',
    companyId: '112c001f-2d8f-456e-aedb-c45bd65f1837',
    jobTitle: 'Junior Specialist',
    companyName: 'DevHaven',
    companyDescription:
      '## O nas\n**DevHaven** — Projektujemy i wdrażamy aplikacje mobilne dla startupów i korporacji.',
    companyLogoUrl: 'https://via.placeholder.com/150?text=DevHaven',
    level: 'lead',
    specialization: 'data-engineering',
    contractType: 'b2b',
    workMode: 'hybrid',
    vacancies: '4',
    technologies: ['java', 'nodejs'],
    technologiesLevels: {
      java: 4,
      nodejs: 4,
    },
    isSalaryRange: true,
    minSalary: 23200,
    maxSalary: 29500,
    salary: 23200,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['italian', 'spanish'],
    languageLevels: {
      italian: 'c1',
      spanish: 'a1',
    },
    positionDescription:
      '## Zakres obowiązków\nTwórz i rozwijaj backend oparty na Node.js i bazach danych NoSQL.',
    address: 'Warszawa, Polska',
    addressLat: 52.2297,
    addressLon: 21.0122,
    createdAt: '2025-05-23',
    isNew: false,
    endDate: '2025-06-16',
  },
  {
    id: 'd33d1313-cfd6-41df-93fc-d0405c7612a0',
    companyId: '93014c93-9851-417a-95ea-a267601bf187',
    jobTitle: 'Mid Engineer',
    companyName: 'TechNova',
    companyDescription:
      '## O nas\n**TechNova** — Jesteśmy software housem specjalizującym się w aplikacjach webowych.',
    companyLogoUrl: 'https://via.placeholder.com/150?text=TechNova',
    level: 'junior',
    specialization: 'pm',
    contractType: 'b2b',
    workMode: 'remote',
    vacancies: '4',
    technologies: ['aws', 'docker', 'sql', 'react', 'typescript'],
    technologiesLevels: {
      aws: 4,
      docker: 1,
      sql: 4,
      react: 2,
      typescript: 3,
    },
    isSalaryRange: true,
    minSalary: 7000,
    maxSalary: 10000,
    salary: 7000,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['english', 'spanish'],
    languageLevels: {
      english: 'c1',
      spanish: 'a2',
    },
    positionDescription:
      '## Zakres obowiązków\nTwórz i rozwijaj backend oparty na Node.js i bazach danych NoSQL.',
    address: 'Kraków, Polska',
    addressLat: 50.0647,
    addressLon: 19.945,
    createdAt: '2025-05-20',
    isNew: false,
    endDate: '2025-06-27',
  },
  {
    id: '45eacd6b-5855-4757-bb42-076b2b051a33',
    companyId: '37f96bbc-e5f4-4db7-bc70-f8f6fd023386',
    jobTitle: 'Senior Developer',
    companyName: 'CloudSpark',
    companyDescription:
      '## O nas\n**CloudSpark** — Nasze produkty wspierają zarządzanie danymi i procesami biznesowymi.',
    companyLogoUrl: 'https://via.placeholder.com/150?text=CloudSpark',
    level: 'mid',
    specialization: 'frontend',
    contractType: 'part-time',
    workMode: 'remote',
    vacancies: '2',
    technologies: ['nodejs', 'aws', 'sql', 'java'],
    technologiesLevels: {
      nodejs: 1,
      aws: 2,
      sql: 2,
      java: 1,
    },
    isSalaryRange: true,
    minSalary: 12600,
    maxSalary: 15700,
    salary: 12600,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['english', 'spanish'],
    languageLevels: {
      english: 'b1',
      spanish: 'c2',
    },
    positionDescription:
      '## Zakres obowiązków\nUczestnicz w procesie tworzenia interfejsów użytkownika zgodnie z wymaganiami UX/UI.',
    address: 'Gdańsk, Polska',
    addressLat: 54.352,
    addressLon: 18.6466,
    createdAt: '2025-05-15',
    isNew: false,
    endDate: '2025-06-18',
  },
  {
    id: 'cefa680c-0123-49c1-b05d-32120592157c',
    companyId: '02d782a6-514e-408c-a4ab-f13297308ec4',
    jobTitle: 'Senior Specialist',
    companyName: 'DataPulse',
    companyDescription:
      '## O nas\n**DataPulse** — Jesteśmy software housem specjalizującym się w aplikacjach webowych.',
    companyLogoUrl: 'https://via.placeholder.com/150?text=DataPulse',
    level: 'senior',
    specialization: 'qa',
    contractType: 'contract',
    workMode: 'office',
    vacancies: '3',
    technologies: ['kubernetes', 'aws', 'docker', 'nodejs'],
    technologiesLevels: {
      kubernetes: 1,
      aws: 5,
      docker: 1,
      nodejs: 2,
    },
    isSalaryRange: true,
    minSalary: 18300,
    maxSalary: 21900,
    salary: 18300,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['spanish', 'french'],
    languageLevels: {
      spanish: 'b2',
      french: 'c1',
    },
    positionDescription:
      '## Zakres obowiązków\nProjektuj architekturę systemu oraz dbaj o wydajność aplikacji.',
    address: 'Kraków, Polska',
    addressLat: 50.0647,
    addressLon: 19.945,
    createdAt: '2025-06-03',
    isNew: false,
    endDate: '2025-07-13',
  },
  {
    id: '912d74c7-f2a9-4edc-bad7-d8988349f2d3',
    companyId: 'b4585a3c-fc35-4a9f-ac6c-426bd220059c',
    jobTitle: 'Mid Engineer',
    companyName: 'NextGenSoft',
    companyDescription:
      '## O nas\n**NextGenSoft** — Tworzymy rozwiązania chmurowe dla branży e-commerce i finansowej.',
    companyLogoUrl: 'https://via.placeholder.com/150?text=NextGenSoft',
    level: 'manager',
    specialization: 'pm',
    contractType: 'part-time',
    workMode: 'office',
    vacancies: '5',
    technologies: ['javascript', 'python', 'docker', 'kubernetes'],
    technologiesLevels: {
      javascript: 4,
      python: 2,
      docker: 4,
      kubernetes: 1,
    },
    isSalaryRange: true,
    minSalary: 31300,
    maxSalary: 34300,
    salary: 31300,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['german', 'italian'],
    languageLevels: {
      german: 'a1',
      italian: 'b1',
    },
    positionDescription:
      '## Zakres obowiązków\nUczestnicz w procesie tworzenia interfejsów użytkownika zgodnie z wymaganiami UX/UI.',
    address: 'Kraków, Polska',
    addressLat: 50.0647,
    addressLon: 19.945,
    createdAt: '2025-06-11',
    isNew: true,
    endDate: '2025-08-08',
  },
  {
    id: 'eaa83453-7f90-418c-b5df-f2e011a735d7',
    companyId: '58e9de1e-a900-4803-9bc4-560c43a5e036',
    jobTitle: 'Senior Engineer',
    companyName: 'BrightApps',
    companyDescription:
      '## O nas\n**BrightApps** — Tworzymy rozwiązania chmurowe dla branży e-commerce i finansowej.',
    companyLogoUrl: 'https://via.placeholder.com/150?text=BrightApps',
    level: 'mid',
    specialization: 'backend',
    contractType: 'b2b',
    workMode: 'office',
    vacancies: '4',
    technologies: ['react', 'aws'],
    technologiesLevels: {
      react: 1,
      aws: 3,
    },
    isSalaryRange: true,
    minSalary: 13700,
    maxSalary: 17500,
    salary: 13700,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['spanish'],
    languageLevels: {
      spanish: 'a1',
    },
    positionDescription:
      '## Zakres obowiązków\nTwórz i rozwijaj backend oparty na Node.js i bazach danych NoSQL.',
    address: 'Gdańsk, Polska',
    addressLat: 54.352,
    addressLon: 18.6466,
    createdAt: '2025-05-22',
    isNew: false,
    endDate: '2025-07-03',
  },
  {
    id: '2a653ce3-fc3e-4953-b610-c89836612de2',
    companyId: '409533c0-d6b7-4926-977a-fbcc279260a7',
    jobTitle: 'Mid Specialist',
    companyName: 'InnoWare',
    companyDescription:
      '## O nas\n**InnoWare** — Jesteśmy software housem specjalizującym się w aplikacjach webowych.',
    companyLogoUrl: 'https://via.placeholder.com/150?text=InnoWare',
    level: 'manager',
    specialization: 'fullstack',
    contractType: 'part-time',
    workMode: 'remote',
    vacancies: '5',
    technologies: ['nodejs', 'aws', 'kubernetes', 'python', 'sql'],
    technologiesLevels: {
      nodejs: 4,
      aws: 3,
      kubernetes: 4,
      python: 1,
      sql: 5,
    },
    isSalaryRange: true,
    minSalary: 28800,
    maxSalary: 33100,
    salary: 28800,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['english', 'french'],
    languageLevels: {
      english: 'b1',
      french: 'a1',
    },
    positionDescription:
      '## Zakres obowiązków\nTwórz i rozwijaj backend oparty na Node.js i bazach danych NoSQL.',
    address: 'Poznań, Polska',
    addressLat: 52.4064,
    addressLon: 16.9252,
    createdAt: '2025-06-04',
    isNew: false,
    endDate: '2025-07-31',
  },
  {
    id: 'ca6acc1a-7914-4416-b788-67ba4e307776',
    companyId: '5949021e-6f8f-4f36-a7fe-28fe2a639e99',
    jobTitle: 'Mid Specialist',
    companyName: 'DigitalCraft',
    companyDescription:
      '## O nas\n**DigitalCraft** — Dostarczamy nowoczesne rozwiązania DevOps dla firm z całej Europy.',
    companyLogoUrl: 'https://via.placeholder.com/150?text=DigitalCraft',
    level: 'lead',
    specialization: 'qa',
    contractType: 'part-time',
    workMode: 'office',
    vacancies: '2',
    technologies: [
      'typescript',
      'javascript',
      'python',
      'kubernetes',
      'nodejs',
    ],
    technologiesLevels: {
      typescript: 3,
      javascript: 2,
      python: 5,
      kubernetes: 4,
      nodejs: 1,
    },
    isSalaryRange: true,
    minSalary: 22800,
    maxSalary: 26300,
    salary: 22800,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['german', 'english'],
    languageLevels: {
      german: 'a2',
      english: 'a2',
    },
    positionDescription:
      '## Zakres obowiązków\nTwórz i rozwijaj backend oparty na Node.js i bazach danych NoSQL.',
    address: 'Berlin, Polska',
    addressLat: 52.52,
    addressLon: 13.405,
    createdAt: '2025-06-11',
    isNew: true,
    endDate: '2025-07-17',
  },
  {
    id: '289898b5-402f-46b0-8841-9e1ec7d4a06a',
    companyId: 'b71d521d-cc2f-4f51-8e71-f0e8cc674ebb',
    jobTitle: 'Junior Developer',
    companyName: 'SkyNetics',
    companyDescription:
      '## O nas\n**SkyNetics** — Dostarczamy nowoczesne rozwiązania DevOps dla firm z całej Europy.',
    companyLogoUrl: 'https://via.placeholder.com/150?text=SkyNetics',
    level: 'junior',
    specialization: 'pm',
    contractType: 'b2b',
    workMode: 'office',
    vacancies: '2',
    technologies: ['python', 'sql', 'typescript'],
    technologiesLevels: {
      python: 5,
      sql: 5,
      typescript: 5,
    },
    isSalaryRange: true,
    minSalary: 6400,
    maxSalary: 10700,
    salary: 6400,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['spanish'],
    languageLevels: {
      spanish: 'a1',
    },
    positionDescription:
      '## Zakres obowiązków\nBędziesz odpowiedzialny/a za rozwój i utrzymanie komponentów frontendowych w React.',
    address: 'Wrocław, Polska',
    addressLat: 51.1079,
    addressLon: 17.0385,
    createdAt: '2025-06-07',
    isNew: true,
    endDate: '2025-07-10',
  },
  {
    id: '880b443a-0d4d-4490-997c-28b3890d223f',
    companyId: 'b89f90fb-a42e-432f-baa4-e77ab3b38962',
    jobTitle: 'Mid Engineer',
    companyName: 'PixelForge',
    companyDescription:
      '## O nas\n**PixelForge** — Tworzymy rozwiązania chmurowe dla branży e-commerce i finansowej.',
    companyLogoUrl: 'https://via.placeholder.com/150?text=PixelForge',
    level: 'manager',
    specialization: 'backend',
    contractType: 'contract',
    workMode: 'remote',
    vacancies: '2',
    technologies: ['aws', 'kubernetes', 'react', 'javascript', 'typescript'],
    technologiesLevels: {
      aws: 5,
      kubernetes: 2,
      react: 3,
      javascript: 5,
      typescript: 2,
    },
    isSalaryRange: true,
    minSalary: 26600,
    maxSalary: 33000,
    salary: 26600,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['french'],
    languageLevels: {
      french: 'a2',
    },
    positionDescription:
      '## Zakres obowiązków\nBędziesz odpowiedzialny/a za rozwój i utrzymanie komponentów frontendowych w React.',
    address: 'Gdańsk, Polska',
    addressLat: 54.352,
    addressLon: 18.6466,
    createdAt: '2025-06-01',
    isNew: false,
    endDate: '2025-06-30',
  },
  {
    id: '3dd6b332-cdb8-4846-8bb9-5aeab30107b3',
    companyId: 'f66ae306-ba29-4ca9-b6a0-cc31a847473a',
    jobTitle: 'Junior Developer',
    companyName: 'DevHaven',
    companyDescription:
      '## O nas\n**DevHaven** — Nasze produkty wspierają zarządzanie danymi i procesami biznesowymi.',
    companyLogoUrl: 'https://via.placeholder.com/150?text=DevHaven',
    level: 'lead',
    specialization: 'pm',
    contractType: 'contract',
    workMode: 'hybrid',
    vacancies: '3',
    technologies: ['typescript', 'java'],
    technologiesLevels: {
      typescript: 1,
      java: 2,
    },
    isSalaryRange: true,
    minSalary: 23300,
    maxSalary: 27600,
    salary: 23300,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['english', 'italian'],
    languageLevels: {
      english: 'b1',
      italian: 'a1',
    },
    positionDescription:
      '## Zakres obowiązków\nUczestnicz w procesie tworzenia interfejsów użytkownika zgodnie z wymaganiami UX/UI.',
    address: 'Kraków, Polska',
    addressLat: 50.0647,
    addressLon: 19.945,
    createdAt: '2025-06-09',
    isNew: true,
    endDate: '2025-07-01',
  },
  {
    id: 'ce822886-8b11-4fc6-bb5d-471f80870f86',
    companyId: '4426542c-9bcd-49c8-91f8-bb8087962354',
    jobTitle: 'Senior Engineer',
    companyName: 'TechNova',
    companyDescription:
      '## O nas\n**TechNova** — Nasze produkty wspierają zarządzanie danymi i procesami biznesowymi.',
    companyLogoUrl: 'https://via.placeholder.com/150?text=TechNova',
    level: 'lead',
    specialization: 'mobile',
    contractType: 'part-time',
    workMode: 'office',
    vacancies: '5',
    technologies: ['docker', 'nodejs', 'aws', 'java'],
    technologiesLevels: {
      docker: 4,
      nodejs: 4,
      aws: 1,
      java: 2,
    },
    isSalaryRange: true,
    minSalary: 22300,
    maxSalary: 26300,
    salary: 22300,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['italian', 'german'],
    languageLevels: {
      italian: 'b1',
      german: 'c2',
    },
    positionDescription:
      '## Zakres obowiązków\nPracuj w zespole SCRUM przy realizacji projektów webowych dla klientów z UE.',
    address: 'Poznań, Polska',
    addressLat: 52.4064,
    addressLon: 16.9252,
    createdAt: '2025-06-13',
    isNew: true,
    endDate: '2025-07-03',
  },
  {
    id: 'c5daa1a5-231e-4193-8334-69b9664d07df',
    companyId: '654af1de-ef3b-483e-b693-1feef86e4229',
    jobTitle: 'Mid Engineer',
    companyName: 'CloudSpark',
    companyDescription:
      '## O nas\n**CloudSpark** — Jesteśmy software housem specjalizującym się w aplikacjach webowych.',
    companyLogoUrl: 'https://via.placeholder.com/150?text=CloudSpark',
    level: 'lead',
    specialization: 'mobile',
    contractType: 'contract',
    workMode: 'hybrid',
    vacancies: '4',
    technologies: ['kubernetes', 'java'],
    technologiesLevels: {
      kubernetes: 3,
      java: 5,
    },
    isSalaryRange: true,
    minSalary: 23400,
    maxSalary: 26800,
    salary: 23400,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['german', 'italian'],
    languageLevels: {
      german: 'c2',
      italian: 'c1',
    },
    positionDescription:
      '## Zakres obowiązków\nBędziesz odpowiedzialny/a za rozwój i utrzymanie komponentów frontendowych w React.',
    address: 'Kraków, Polska',
    addressLat: 50.0647,
    addressLon: 19.945,
    createdAt: '2025-06-13',
    isNew: true,
    endDate: '2025-08-08',
  },
  {
    id: '797a087f-fcab-424b-b63e-1381844f442e',
    companyId: '3f4580b0-f38e-4217-b73e-3d4035df9430',
    jobTitle: 'Senior Specialist',
    companyName: 'DataPulse',
    companyDescription:
      '## O nas\n**DataPulse** — Tworzymy rozwiązania chmurowe dla branży e-commerce i finansowej.',
    companyLogoUrl: 'https://via.placeholder.com/150?text=DataPulse',
    level: 'intern',
    specialization: 'data-engineering',
    contractType: 'full-time',
    workMode: 'hybrid',
    vacancies: '1',
    technologies: ['react', 'javascript', 'nodejs', 'java', 'python'],
    technologiesLevels: {
      react: 2,
      javascript: 2,
      nodejs: 4,
      java: 3,
      python: 5,
    },
    isSalaryRange: true,
    minSalary: 4900,
    maxSalary: 6000,
    salary: 4900,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['french', 'spanish'],
    languageLevels: {
      french: 'b2',
      spanish: 'a2',
    },
    positionDescription:
      '## Zakres obowiązków\nPracuj w zespole SCRUM przy realizacji projektów webowych dla klientów z UE.',
    address: 'Berlin, Polska',
    addressLat: 52.52,
    addressLon: 13.405,
    createdAt: '2025-05-28',
    isNew: false,
    endDate: '2025-07-05',
  },
  {
    id: '747d599c-d477-4fd4-aa20-e640e406d82d',
    companyId: '477bd8c3-0203-413b-853b-7fe166cae75b',
    jobTitle: 'Junior Engineer',
    companyName: 'NextGenSoft',
    companyDescription:
      '## O nas\n**NextGenSoft** — Jesteśmy software housem specjalizującym się w aplikacjach webowych.',
    companyLogoUrl: 'https://via.placeholder.com/150?text=NextGenSoft',
    level: 'senior',
    specialization: 'mobile',
    contractType: 'internship',
    workMode: 'hybrid',
    vacancies: '4',
    technologies: ['react', 'kubernetes', 'python', 'docker', 'typescript'],
    technologiesLevels: {
      react: 2,
      kubernetes: 4,
      python: 1,
      docker: 3,
      typescript: 2,
    },
    isSalaryRange: true,
    minSalary: 19300,
    maxSalary: 24900,
    salary: 19300,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['english', 'french'],
    languageLevels: {
      english: 'c2',
      french: 'b1',
    },
    positionDescription:
      '## Zakres obowiązków\nBędziesz odpowiedzialny/a za rozwój i utrzymanie komponentów frontendowych w React.',
    address: 'Gdańsk, Polska',
    addressLat: 54.352,
    addressLon: 18.6466,
    createdAt: '2025-05-19',
    isNew: false,
    endDate: '2025-07-05',
  },
  {
    id: '9dea5c25-d196-4df8-99b1-847e0d55911c',
    companyId: '16fd6f35-779d-4fbd-84ac-dd9329d01167',
    jobTitle: 'Mid Specialist',
    companyName: 'BrightApps',
    companyDescription:
      '## O nas\n**BrightApps** — Projektujemy i wdrażamy aplikacje mobilne dla startupów i korporacji.',
    companyLogoUrl: 'https://via.placeholder.com/150?text=BrightApps',
    level: 'mid',
    specialization: 'qa',
    contractType: 'b2b',
    workMode: 'office',
    vacancies: '2',
    technologies: ['kubernetes', 'nodejs', 'docker', 'java', 'sql'],
    technologiesLevels: {
      kubernetes: 1,
      nodejs: 3,
      docker: 2,
      java: 5,
      sql: 1,
    },
    isSalaryRange: true,
    minSalary: 13800,
    maxSalary: 17200,
    salary: 13800,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['english'],
    languageLevels: {
      english: 'a2',
    },
    positionDescription:
      '## Zakres obowiązków\nTwórz i rozwijaj backend oparty na Node.js i bazach danych NoSQL.',
    address: 'Gdańsk, Polska',
    addressLat: 54.352,
    addressLon: 18.6466,
    createdAt: '2025-06-07',
    isNew: true,
    endDate: '2025-07-14',
  },
  {
    id: 'd1dd6371-c74f-4ce2-b696-fddfc6b2c530',
    companyId: '6f2d14ca-2064-46be-afc5-413bf01292ed',
    jobTitle: 'Junior Developer',
    companyName: 'InnoWare',
    companyDescription:
      '## O nas\n**InnoWare** — Dostarczamy nowoczesne rozwiązania DevOps dla firm z całej Europy.',
    companyLogoUrl: 'https://via.placeholder.com/150?text=InnoWare',
    level: 'junior',
    specialization: 'fullstack',
    contractType: 'full-time',
    workMode: 'hybrid',
    vacancies: '3',
    technologies: ['python', 'kubernetes', 'nodejs', 'sql', 'javascript'],
    technologiesLevels: {
      python: 1,
      kubernetes: 1,
      nodejs: 2,
      sql: 4,
      javascript: 1,
    },
    isSalaryRange: true,
    minSalary: 5700,
    maxSalary: 10700,
    salary: 5700,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['german', 'spanish'],
    languageLevels: {
      german: 'c2',
      spanish: 'b2',
    },
    positionDescription:
      '## Zakres obowiązków\nProjektuj architekturę systemu oraz dbaj o wydajność aplikacji.',
    address: 'Poznań, Polska',
    addressLat: 52.4064,
    addressLon: 16.9252,
    createdAt: '2025-06-02',
    isNew: false,
    endDate: '2025-06-17',
  },
  {
    id: '8a75e26a-44b0-4e56-8269-065cc293cad6',
    companyId: '194c4389-354c-40d5-a95c-e3a9936bac15',
    jobTitle: 'Mid Specialist',
    companyName: 'DigitalCraft',
    companyDescription:
      '## O nas\n**DigitalCraft** — Tworzymy rozwiązania chmurowe dla branży e-commerce i finansowej.',
    companyLogoUrl: 'https://via.placeholder.com/150?text=DigitalCraft',
    level: 'lead',
    specialization: 'frontend',
    contractType: 'full-time',
    workMode: 'remote',
    vacancies: '2',
    technologies: ['docker', 'sql', 'react', 'javascript'],
    technologiesLevels: {
      docker: 2,
      sql: 4,
      react: 1,
      javascript: 4,
    },
    isSalaryRange: true,
    minSalary: 23000,
    maxSalary: 28100,
    salary: 23000,
    currency: 'pln',
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['italian'],
    languageLevels: {
      italian: 'c2',
    },
    positionDescription:
      '## Zakres obowiązków\nBędziesz odpowiedzialny/a za rozwój i utrzymanie komponentów frontendowych w React.',
    address: 'Wrocław, Polska',
    addressLat: 51.1079,
    addressLon: 17.0385,
    createdAt: '2025-05-26',
    isNew: false,
    endDate: '2025-07-15',
  },
];
