import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import { Navbar } from '@/components/layout/Navbar/Navbar';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import { Toaster } from 'sonner';
import { I18nProvider } from './i18n-provider';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600'],
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${poppins.className} antialiased`}
        suppressHydrationWarning
      >
        <I18nProvider>
          <ThemeProvider
            attribute='class'
            defaultTheme='system'
            enableSystem
            disableTransitionOnChange
          >
            <Navbar />
            <Toaster richColors position='bottom-right' />
            <main className='pt-16'>{children}</main>
          </ThemeProvider>
        </I18nProvider>
      </body>
    </html>
  );
}
