import { CandidateData } from './components';

export const candidatesConfig: CandidateData[] = [
  {
    id: '498d9fac-208c-4e14-b90d-fe84470919f1',
    fullName: 'Krzysztof Kononowicz',
    title: 'Junior Frontend Developer',
    level: ['junior', 'mid'],
    photoUrl: '/images/human1.png',
    specialization: ['backend', 'frontend', 'fullstack'],
    contractType: ['full-time'],
    workMode: ['remote', 'hybrid'],
    technologies: ['javascript', 'typescript', 'react'],
    technologiesLevels: {
      javascript: 2,
      typescript: 5,
      react: 3,
      nodejs: 3,
    },
    minSalary: 7500,
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['english'],
    languageLevels: {
      english: 'c1',
    },
    candidateDescription:
      '## Zakres obowiązków\nProjektuj architekturę systemu oraz dbaj o wydajność aplikacji.',
    city: 'Wrocław',
    country: 'Polska',
  },
  {
    id: 'a7f2b8c9-3d4e-5f6a-8b9c-1d2e3f4a5b6c',
    fullName: 'Wojciech Suchodolski',
    title: 'Mid Fullstack Developer',
    level: ['junior', 'mid'],
    photoUrl: '/images/human2.png',
    specialization: ['backend', 'frontend', 'fullstack'],
    contractType: ['full-time'],
    workMode: ['office'],
    technologies: ['javascript', 'typescript', 'react', 'nodejs', 'git'],
    technologiesLevels: {
      javascript: 4,
      typescript: 3,
      react: 4,
      nodejs: 2,
    },
    minSalary: 9500,
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['english'],
    languageLevels: {
      english: 'b2',
    },
    candidateDescription:
      '## Zakres obowiązków\nRozwój aplikacji webowych z wykorzystaniem nowoczesnych technologii frontend i backend.',
    city: 'Warszawa',
    country: 'Polska',
  },
  {
    id: 'b8c9d0e1-4f5a-6b7c-9d0e-2f3a4b5c6d7e',
    fullName: 'Marcin Wiśniewski',
    title: 'Junior DevOps Engineer',
    level: ['junior', 'mid'],
    photoUrl: '/images/human3.png',
    specialization: ['devops'],
    contractType: ['full-time'],
    workMode: ['remote'],
    technologies: ['docker', 'kubernetes', 'jenkins', 'aws', 'linux', 'git'],
    technologiesLevels: {
      docker: 3,
      kubernetes: 2,
      jenkins: 2,
      aws: 2,
      linux: 3,
      git: 4,
    },
    minSalary: 6800,
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['english'],
    languageLevels: {
      english: 'c1',
    },
    candidateDescription:
      '## Zakres obowiązków\nTworzenie skalowalnych rozwiązań backend oraz integracja z systemami zewnętrznymi.',
    city: 'Kraków',
    country: 'Polska',
  },
  {
    id: 'c9d0e1f2-5a6b-7c8d-0e1f-3a4b5c6d7e8f',
    fullName: 'Katarzyna Dąbrowska',
    title: 'Mid PHP Developer',
    level: ['junior', 'mid'],
    photoUrl: '/images/human4.png',
    specialization: ['backend', 'fullstack'],
    contractType: ['full-time'],
    workMode: ['remote'],
    technologies: ['php', 'angular', 'sql', 'javascript', 'git'],
    technologiesLevels: {
      javascript: 5,
      typescript: 2,
      react: 5,
      nodejs: 3,
    },
    minSalary: 11000,
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['english'],
    languageLevels: {
      english: 'c2',
    },
    candidateDescription:
      '## Zakres obowiązków\nOptymalizacja wydajności aplikacji oraz implementacja najlepszych praktyk programistycznych.',
    city: 'Gdańsk',
    country: 'Polska',
  },
  {
    id: 'd0e1f2a3-6b7c-8d9e-1f2a-4b5c6d7e8f9a',
    fullName: 'Tomasz Lewandowski',
    title: 'Senior Frontend Developer',
    level: ['senior'],
    photoUrl: '/images/human9.png',
    specialization: ['frontend'],
    contractType: ['full-time'],
    workMode: ['remote'],
    technologies: ['react', 'typescript', 'angular', 'vue', 'git'],
    technologiesLevels: {
      javascript: 3,
      typescript: 3,
      react: 3,
      nodejs: 5,
    },
    minSalary: 16200,
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['english'],
    languageLevels: {
      english: 'b2',
    },
    candidateDescription:
      '## Zakres obowiązków\nWdrażanie nowych funkcjonalności oraz utrzymanie istniejących systemów informatycznych.',
    city: 'Poznań',
    country: 'Polska',
  },
  {
    id: 'e1f2a3b4-7c8d-9e0f-2a3b-5c6d7e8f9a0b',
    fullName: 'Piotr Zieliński',
    title: 'Junior Fullstack Developer',
    level: ['junior', 'mid'],
    photoUrl: '/images/human7.png',
    specialization: ['backend', 'frontend', 'fullstack'],
    contractType: ['full-time'],
    workMode: ['remote'],
    technologies: ['javascript', 'typescript', 'react', 'nodejs'],
    technologiesLevels: {
      javascript: 4,
      typescript: 4,
      react: 4,
      nodejs: 2,
    },
    minSalary: 7000,
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['english'],
    languageLevels: {
      english: 'c1',
    },
    candidateDescription:
      '## Zakres obowiązków\nAnaliza wymagań biznesowych i przekładanie ich na rozwiązania techniczne.',
    city: 'Łódź',
    country: 'Polska',
  },
  {
    id: 'f2a3b4c5-8d9e-0f1a-3b4c-6d7e8f9a0b1c',
    fullName: 'Paweł Szymański',
    title: 'Mid Fullstack Developer',
    level: ['junior', 'mid'],
    photoUrl: '/images/human8.png',
    specialization: ['backend', 'frontend', 'fullstack'],
    contractType: ['full-time'],
    workMode: ['remote'],
    technologies: ['javascript', 'typescript', 'react', 'nodejs'],
    technologiesLevels: {
      javascript: 2,
      typescript: 5,
      react: 3,
      nodejs: 4,
    },
    minSalary: 6300,
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['english'],
    languageLevels: {
      english: 'b2',
    },
    candidateDescription:
      '## Zakres obowiązków\nUczestnictwo w całym cyklu rozwoju oprogramowania od planowania po wdrożenie.',
    city: 'Szczecin',
    country: 'Polska',
  },
  {
    id: 'a3b4c5d6-9e0f-1a2b-4c5d-7e8f9a0b1c2d',
    fullName: 'Magdalena Wojciechowska',
    title: 'Senior Fullstack Developer',
    level: ['junior', 'mid'],
    photoUrl: '/images/human9.png',
    specialization: ['backend', 'frontend', 'fullstack'],
    contractType: ['full-time'],
    workMode: ['remote'],
    technologies: ['javascript', 'typescript', 'react', 'nodejs'],
    technologiesLevels: {
      javascript: 5,
      typescript: 3,
      react: 2,
      nodejs: 3,
    },
    minSalary: 6900,
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['english'],
    languageLevels: {
      english: 'c1',
    },
    candidateDescription:
      '## Zakres obowiązków\nKoordynacja prac zespołu developerskiego oraz mentoring młodszych programistów.',
    city: 'Katowice',
    country: 'Polska',
  },
  {
    id: 'b4c5d6e7-0f1a-2b3c-5d6e-8f9a0b1c2d3e',
    fullName: 'Łukasz Kaczmarek',
    title: 'Mid Fullstack Developer',
    level: ['junior', 'mid'],
    photoUrl: '/images/human8.png',
    specialization: ['backend', 'frontend', 'fullstack'],
    contractType: ['full-time'],
    workMode: ['remote'],
    technologies: ['javascript', 'typescript', 'react', 'nodejs'],
    technologiesLevels: {
      javascript: 3,
      typescript: 4,
      react: 5,
      nodejs: 2,
    },
    minSalary: 7100,
    isSalaryShown: true,
    salaryPeriod: 'perMonth',
    languages: ['english'],
    languageLevels: {
      english: 'b2',
    },
    candidateDescription:
      '## Zakres obowiązków\nTworzenie responsywnych interfejsów użytkownika oraz integracja z API backend.',
    city: 'Lublin',
    country: 'Polska',
  },
];
